import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Upload, Search, CheckCircle, AlertCircle, ArrowLeft, TrendingUp, AlertTriangle, Lightbulb, Cpu, Download, FileText } from 'lucide-react'

export default function Analyze() {
  const [file, setFile] = useState(null)
  const [loading, setLoading] = useState(false)
  const [results, setResults] = useState(null)
  const [error, setError] = useState('')
  const [dragOver, setDragOver] = useState(false)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!file) {
      setError('Please upload a resume file')
      return
    }

    setLoading(true)
    setError('')
    setResults(null)

    const formData = new FormData()
    formData.append('resume', file)

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        body: formData
      })
      const text = await response.text()
      if (!text || text.trim() === '') throw new Error('Empty response from server')

      let data;
      try {
        data = JSON.parse(text);
      } catch (e) {
        throw new Error('Invalid JSON response from server')
      }

      if (!response.ok) throw new Error(data.error || 'Failed to analyze')

      setResults(data)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const downloadReport = () => {
    const report = `╔══════════════════════════════════════════════════════════════╗
║                AI RESUME ANALYZER - ANALYSIS REPORT            ║
╚══════════════════════════════════════════════════════════════╝

GENERATED: ${new Date().toLocaleDateString()}

${'─'.repeat(66)}
📊 OVERALL SCORE
${'─'.repeat(66)}
Score: ${results.score || 0}/100

${'─'.repeat(66)}
💪 STRENGTHS
${'─'.repeat(66)}
${results.strengths?.map(s => `  • ${s}`).join('\n') || '  N/A'}

${'─'.repeat(66)}
⚠️ AREAS TO IMPROVE
${'─'.repeat(66)}
${results.weaknesses?.map(w => `  • ${w}`).join('\n') || '  N/A'}

${'─'.repeat(66)}
💡 SUGGESTIONS
${'─'.repeat(66)}
${results.suggestions?.map(s => `  • ${s}`).join('\n') || '  N/A'}

${'─'.repeat(66)}
🔑 MISSING KEYWORDS
${'─'.repeat(66)}
${results.keywords_found?.map(k => `  • ${k}`).join('\n') || '  N/A'}

${'─'.repeat(66)}
🤖 ATS SCORE
${'─'.repeat(66)}
ATS Score: ${results.ATS_score || 0}/100

${'─'.repeat(66)}
💼 JOB RECOMMENDATIONS
${'─'.repeat(66)}
${results.job_recommendations?.map(j => `  • ${j}`).join('\n') || '  N/A'}

═══════════════════════════════════════════════════════════════
          Generated by AI Resume Builder
═══════════════════════════════════════════════════════════════
`
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'resume-analysis-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="py-12 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Back link */}
        <Link to="/" className="inline-flex items-center gap-2 text-text-muted hover:text-text-light transition-colors mb-8 animate-slide-in-left">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        {/* Header */}
        <div className="flex items-center gap-4 mb-8 animate-slide-up">
          <div className="w-16 h-16 rounded-xl bg-gradient-to-r from-blue-500 to-indigo-500 flex items-center justify-center animate-float">
            <Search className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Resume Analyzer</h1>
            <p className="text-text-muted">Upload your resume and get AI-powered analysis with detailed feedback</p>
          </div>
        </div>

        {/* Form Card */}
        <div className="bg-bg-card border border-border rounded-2xl p-6 sm:p-8 animate-slide-up delay-100 card-lift">
          <form onSubmit={handleSubmit}>
            <div
              className={`file-upload rounded-xl p-8 text-center mb-6 transition-all duration-300 ${dragOver ? 'dragover' : ''}`}
              onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
              onDragLeave={() => setDragOver(false)}
              onDrop={(e) => {
                e.preventDefault()
                setDragOver(false)
                const droppedFile = e.dataTransfer.files[0]
                if (droppedFile) setFile(droppedFile)
              }}
            >
              <input
                type="file"
                accept=".pdf,.txt"
                onChange={(e) => setFile(e.target.files[0])}
                className="hidden"
                id="resume-upload"
              />
              <label htmlFor="resume-upload" className="cursor-pointer">
                <Upload className={`w-12 h-12 mx-auto mb-3 transition-colors ${dragOver ? 'text-primary' : 'text-text-muted'}`} />
                <p className="text-text-muted">Drag & drop your resume or click to browse</p>
                <p className="text-sm text-text-muted mt-2">Supports PDF & TXT files</p>
                {file && (
                  <p className="text-secondary mt-3 font-medium flex items-center justify-center gap-2 animate-scale-in">
                    <CheckCircle className="w-4 h-4" /> {file.name}
                  </p>
                )}
              </label>
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn-gradient w-full py-4 rounded-xl font-semibold text-white flex items-center justify-center gap-2 disabled:opacity-50 btn-press transition-all duration-300 animate-slide-up delay-200"
            >
              {loading ? (
                <>
                  <div className="spinner w-5 h-5" />
                  <span>Analyzing Resume...</span>
                </>
              ) : (
                <>
                  <Search className="w-5 h-5" />
                  <span>Analyze Resume</span>
                </>
              )}
            </button>
          </form>

          {error && (
            <div className="mt-4 p-4 bg-red-500/10 border border-red-500 rounded-xl text-red-400 flex items-center gap-2 animate-scale-in">
              <AlertCircle className="w-5 h-5" /> {error}
            </div>
          )}
        </div>

        {/* Loading Skeleton */}
        {loading && (
          <div className="mt-8 space-y-6 animate-fade-in">
            <div className="bg-bg-card border border-border rounded-2xl p-6">
              <div className="flex items-center gap-4">
                <div className="w-20 h-20 rounded-full bg-bg-dark animate-shimmer" />
                <div className="space-y-3 flex-1">
                  <div className="h-5 bg-bg-dark rounded w-3/4 animate-shimmer" />
                  <div className="h-4 bg-bg-dark rounded w-1/2 animate-shimmer" />
                </div>
              </div>
            </div>
            <div className="bg-bg-card border border-border rounded-2xl p-6">
              <div className="h-5 bg-bg-dark rounded w-1/4 mb-4 animate-shimmer" />
              <div className="space-y-3">
                <div className="h-4 bg-bg-dark rounded animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-5/6 animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-4/6 animate-shimmer" />
              </div>
            </div>
          </div>
        )}

        {/* Results */}
        {results && (
          <div className="mt-8 space-y-6">
            {/* Score Cards */}
            <div className="grid sm:grid-cols-2 gap-6">
              {/* Overall Score */}
              <div className="bg-bg-card border border-border rounded-2xl p-6 animate-scale-in card-lift">
                <div className="flex items-center gap-4">
                  <div className="relative">
                    <div className="w-20 h-20 rounded-full bg-bg-dark flex items-center justify-center">
                      <span className="text-3xl font-bold gradient-text">{results.score || 0}</span>
                    </div>
                    <div className="absolute inset-0 rounded-full border-4 border-primary/30 animate-pulse-ring" />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold">Overall Score</h3>
                    <p className="text-sm text-text-muted">Resume quality rating</p>
                    <div className="flex items-center gap-1 mt-2 text-emerald-400">
                      <TrendingUp className="w-4 h-4" />
                      <span className="text-sm font-medium">
                        {results.score >= 70 ? 'Good' : results.score >= 50 ? 'Average' : 'Needs Work'}
                      </span>
                    </div>
                  </div>
                </div>
              </div>

              {/* ATS Score */}
              {results.ATS_score && (
                <div className="bg-bg-card border border-border rounded-2xl p-6 animate-scale-in delay-100 card-lift">
                  <div className="flex items-center gap-4">
                    <div className="relative">
                      <div className="w-20 h-20 rounded-full bg-bg-dark flex items-center justify-center">
                        <Cpu className="w-8 h-8 text-primary" />
                      </div>
                      <div className="absolute inset-0 rounded-full border-4 border-primary/30 animate-pulse-ring" />
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold">ATS Score</h3>
                      <p className="text-sm text-text-muted">ATS compatibility</p>
                      <div className="flex items-center gap-1 mt-2 text-violet-400">
                        <span className="text-2xl font-bold">{results.ATS_score}</span>
                        <span className="text-sm">/100</span>
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* Strengths */}
            {results.strengths?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-100 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-emerald-500 to-teal-500 flex items-center justify-center">
                    <CheckCircle className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Strengths</h4>
                    <p className="text-sm text-text-muted">{results.strengths.length} areas excelling</p>
                  </div>
                </div>
                <div className="p-5">
                  <ul className="space-y-3">
                    {results.strengths.map((item, i) => (
                      <li
                        key={i}
                        className="bg-bg-dark/50 p-4 rounded-xl border-l-4 border-emerald-500 hover:translate-x-2 transition-transform duration-300"
                        style={{ animationDelay: `${i * 100}ms` }}
                      >
                        <span className="text-text-light">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}

            {/* Weaknesses */}
            {results.weaknesses?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-200 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-amber-500 to-orange-500 flex items-center justify-center">
                    <AlertTriangle className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Areas to Improve</h4>
                    <p className="text-sm text-text-muted">{results.weaknesses.length} suggestions</p>
                  </div>
                </div>
                <div className="p-5">
                  <ul className="space-y-3">
                    {results.weaknesses.map((item, i) => (
                      <li
                        key={i}
                        className="bg-bg-dark/50 p-4 rounded-xl border-l-4 border-amber-500 hover:translate-x-2 transition-transform duration-300"
                        style={{ animationDelay: `${i * 100}ms` }}
                      >
                        <span className="text-text-light">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}

            {/* Suggestions */}
            {results.suggestions?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-300 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-blue-500 to-indigo-500 flex items-center justify-center">
                    <Lightbulb className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Suggestions</h4>
                    <p className="text-sm text-text-muted">{results.suggestions.length} recommendations</p>
                  </div>
                </div>
                <div className="p-5">
                  <ul className="space-y-3">
                    {results.suggestions.map((item, i) => (
                      <li
                        key={i}
                        className="bg-bg-dark/50 p-4 rounded-xl border-l-4 border-blue-500 hover:translate-x-2 transition-transform duration-300"
                        style={{ animationDelay: `${i * 100}ms` }}
                      >
                        <span className="text-text-light">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}

            {/* Missing Keywords */}
            {results.keywords_found?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-400 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-violet-500 to-purple-500 flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                    </svg>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Missing Keywords</h4>
                    <p className="text-sm text-text-muted">{results.keywords_found.length} keywords for ATS</p>
                  </div>
                </div>
                <div className="p-5">
                  <div className="flex flex-wrap gap-3">
                    {results.keywords_found.map((kw, i) => (
                      <span
                        key={i}
                        className="px-4 py-2 bg-gradient-to-r from-violet-500/20 to-purple-500/20 border border-violet-500/30 rounded-full text-purple-300 text-sm font-medium hover:scale-105 transition-transform duration-300"
                        style={{ animationDelay: `${i * 50}ms` }}
                      >
                        {kw}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Job Recommendations */}
            {results.job_recommendations?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-500 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-pink-500 to-rose-500 flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.175-.126-8.955-.321a2.72 2.72 0 001.176 2.321 2.72 2.72 0 012.291.633 23.914 23.914 0 0110.407 2.186 2.722 2.722 0 01-1.28 2.452 2.722 2.722 0 00-1.32 2.087 23.93 23.93 0 01-3.592.572 2.722 2.722 0 002.004 1.532A23.946 23.946 0 0112 22c2.387 0 4.794-.34 7.063-.946a2.72 2.72 0 01-1.55-.246 2.722 2.722 0 00-1.02-.094 23.93 23.93 0 013.55-1.008 2.722 2.722 0 01-2.156-1.57 2.72 2.72 0 012.959-1.066c2.76.68 5.422.93 8.14.633a2.72 2.72 0 01-1.55-.246 2.72 2.72 0 00-1.02-.094 23.93 23.93 0 01-3.55-1.008 2.722 2.722 0 012.156-1.57 2.72 2.72 0 00-1.02-.094" />
                    </svg>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Job Recommendations</h4>
                    <p className="text-sm text-text-muted">Suggested roles based on your profile</p>
                  </div>
                </div>
                <div className="p-5">
                  <div className="flex flex-wrap gap-3">
                    {results.job_recommendations.map((job, i) => (
                      <span
                        key={i}
                        className="px-4 py-2 bg-gradient-to-r from-pink-500/20 to-rose-500/20 border border-pink-500/30 rounded-full text-pink-300 text-sm font-medium hover:scale-105 transition-transform duration-300"
                        style={{ animationDelay: `${i * 50}ms` }}
                      >
                        {job}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Download Report Button */}
            <button
              onClick={downloadReport}
              className="w-full py-4 rounded-xl font-semibold text-white bg-gradient-to-r from-emerald-500 to-teal-500 flex items-center justify-center gap-2 hover:shadow-lg hover:shadow-emerald-500/30 transition-all duration-300 btn-press animate-slide-up delay-500"
            >
              <FileText className="w-5 h-5" />
              Download Full Report
            </button>
          </div>
        )}
      </div>
    </div>
  )
}
