import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Sparkles, Copy, CheckCircle, AlertCircle, ArrowLeft, FileText, FileDown } from 'lucide-react'

export default function Build() {
  const [resumeText, setResumeText] = useState('')
  const [jobTitle, setJobTitle] = useState('')
  const [improvements, setImprovements] = useState('')
  const [loading, setLoading] = useState(false)
  const [results, setResults] = useState(null)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!resumeText.trim()) {
      setError('Please enter your resume text')
      return
    }

    setLoading(true)
    setError('')
    setResults(null)

    try {
      const response = await fetch('/api/build', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeText, jobTitle, improvements })
      })
      const text = await response.text()
      if (!text) throw new Error('Empty response from server')

      let data;
      try {
        data = JSON.parse(text);
      } catch (e) {
        throw new Error('Invalid JSON from server: ' + text.substring(0, 100));
      }

      if (!response.ok) throw new Error(data.error || data.raw_response || 'Failed to build')

      if (!data.improved_resume) throw new Error(data.raw_response || 'Invalid response format')

      setResults(data)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(results.improved_resume)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadAsText = () => {
    const content = `AI-ENHANCED RESUME
${'='.repeat(50)}

${results.improved_resume}

${'='.repeat(50)}
KEY CHANGES MADE
${'='.repeat(50)}
${results.changes_explanation || 'N/A'}

${'='.repeat(50)}
ATS KEYWORDS ADDED
${'='.repeat(50)}
${results.added_keywords?.join(', ') || 'N/A'}
`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'improved-resume.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  const downloadFullReport = () => {
    const keywordsList = results.added_keywords?.map(kw => `  • ${kw}`).join('\n') || '  • N/A'
    const report = `╔══════════════════════════════════════════════════════════════╗
║              AI RESUME BUILDER - ENHANCEMENT REPORT            ║
╚══════════════════════════════════════════════════════════════╝

GENERATED: ${new Date().toLocaleDateString()} | Target Job: ${jobTitle || 'General'}

${'─'.repeat(66)}
📋 IMPROVED RESUME
${'─'.repeat(66)}
${results.improved_resume}

${'─'.repeat(66)}
📝 KEY CHANGES MADE
${'─'.repeat(66)}
${results.changes_explanation || 'N/A'}

${'─'.repeat(66)}
🔑 ATS KEYWORDS ADDED (${results.added_keywords?.length || 0})
${'─'.repeat(66)}
${keywordsList}

${'─'.repeat(66)}
SUMMARY
${'─'.repeat(66)}
• Resume enhanced for: ${jobTitle || 'General Applications'}
• Keywords optimized for ATS screening
• Professional formatting applied
• Quantified achievements where applicable

═══════════════════════════════════════════════════════════════
          Generated by AI Resume Builder
═══════════════════════════════════════════════════════════════
`
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'resume-enhancement-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="py-12 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Back link */}
        <Link to="/" className="inline-flex items-center gap-2 text-text-muted hover:text-text-light transition-colors mb-8 animate-slide-in-left">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        {/* Header */}
        <div className="flex items-center gap-4 mb-8 animate-slide-up">
          <div className="w-16 h-16 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-500 flex items-center justify-center animate-float">
            <Sparkles className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Build & Improve Resume</h1>
            <p className="text-text-muted">Enhance your resume for specific job applications with AI</p>
          </div>
        </div>

        {/* Form Card */}
        <div className="bg-bg-card border border-border rounded-2xl p-6 sm:p-8 animate-slide-up delay-100 card-lift">
          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="animate-slide-up delay-100">
              <label className="block text-text-muted mb-2 font-medium">Target Job Title</label>
              <input
                type="text"
                value={jobTitle}
                onChange={(e) => setJobTitle(e.target.value)}
                placeholder="e.g., Software Engineer"
                className="w-full bg-bg-dark border border-border rounded-xl px-4 py-3 text-text-light focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all"
              />
            </div>

            <div className="animate-slide-up delay-200">
              <label className="block text-text-muted mb-2 font-medium">Current Resume Text</label>
              <textarea
                value={resumeText}
                onChange={(e) => setResumeText(e.target.value)}
                placeholder="Paste your current resume here..."
                rows={8}
                className="w-full bg-bg-dark border border-border rounded-xl px-4 py-3 text-text-light focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all resize-none"
              />
            </div>

            <div className="animate-slide-up delay-300">
              <label className="block text-text-muted mb-2 font-medium">Specific Improvements (Optional)</label>
              <input
                type="text"
                value={improvements}
                onChange={(e) => setImprovements(e.target.value)}
                placeholder="e.g., Make it more concise, add more metrics"
                className="w-full bg-bg-dark border border-border rounded-xl px-4 py-3 text-text-light focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn-gradient w-full py-4 rounded-xl font-semibold text-white flex items-center justify-center gap-2 disabled:opacity-50 btn-press transition-all duration-300 animate-slide-up delay-400"
            >
              {loading ? (
                <>
                  <div className="spinner w-5 h-5" />
                  <span>Enhancing Resume...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  <span>Improve Resume</span>
                </>
              )}
            </button>
          </form>

          {error && (
            <div className="mt-4 p-4 bg-red-500/10 border border-red-500 rounded-xl text-red-400 flex items-center gap-2 animate-scale-in">
              <AlertCircle className="w-5 h-5" /> {error}
            </div>
          )}
        </div>

        {/* Loading Skeleton */}
        {loading && (
          <div className="mt-8 space-y-6 animate-fade-in">
            <div className="bg-bg-card border border-border rounded-2xl overflow-hidden">
              <div className="p-5 border-b border-border">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-bg-dark animate-shimmer" />
                  <div className="space-y-2">
                    <div className="h-4 w-32 bg-bg-dark rounded animate-shimmer" />
                    <div className="h-3 w-24 bg-bg-dark rounded animate-shimmer" />
                  </div>
                </div>
              </div>
              <div className="p-5 space-y-3">
                <div className="h-4 bg-bg-dark rounded animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-5/6 animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-4/6 animate-shimmer" />
              </div>
            </div>
          </div>
        )}

        {/* Results */}
        {results && (
          <div className="mt-8 space-y-6">
            {/* Improved Resume Card */}
            <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-scale-in card-lift">
              <div className="flex items-center justify-between p-5 border-b border-border">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-emerald-500 to-teal-500 flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Improved Resume</h4>
                    <p className="text-sm text-text-muted">AI-enhanced version</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={downloadAsText}
                    className="flex items-center gap-2 px-3 py-2 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-lg text-emerald-400 transition-all duration-300 btn-press"
                  >
                    <FileText className="w-4 h-4" /> Resume
                  </button>
                  <button
                    onClick={downloadFullReport}
                    className="flex items-center gap-2 px-3 py-2 bg-violet-500/10 hover:bg-violet-500/20 rounded-lg text-violet-400 transition-all duration-300 btn-press"
                  >
                    <FileDown className="w-4 h-4" /> Full Report
                  </button>
                  <button
                    onClick={copyToClipboard}
                    className="flex items-center gap-2 px-4 py-2 bg-primary/10 hover:bg-primary/20 rounded-lg text-primary transition-all duration-300 btn-press"
                  >
                    {copied ? <CheckCircle className="w-4 h-4 animate-scale-in" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                </div>
              </div>
              <div className="p-5 bg-bg-dark/50">
                <pre className="whitespace-pre-wrap text-text-light leading-relaxed font-mono text-sm">{results.improved_resume}</pre>
              </div>
            </div>

            {/* Changes Explanation Card */}
            {results.changes_explanation && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-100 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-amber-500 to-orange-500 flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
                    </svg>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Key Changes Made</h4>
                    <p className="text-sm text-text-muted">What was improved</p>
                  </div>
                </div>
                <div className="p-5">
                  <p className="text-text-light leading-relaxed">{results.changes_explanation}</p>
                </div>
              </div>
            )}

            {/* Added Keywords Card */}
            {results.added_keywords?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-200 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-violet-500 to-purple-500 flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
                    </svg>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">ATS Keywords Added</h4>
                    <p className="text-sm text-text-muted">{results.added_keywords.length} keywords for better visibility</p>
                  </div>
                </div>
                <div className="p-5">
                  <div className="flex flex-wrap gap-3">
                    {results.added_keywords.map((kw, i) => (
                      <span
                        key={i}
                        className="px-4 py-2 bg-gradient-to-r from-violet-500/20 to-purple-500/20 border border-violet-500/30 rounded-full text-purple-300 text-sm font-medium hover:scale-105 transition-transform duration-300 cursor-default"
                        style={{ animationDelay: `${i * 50}ms` }}
                      >
                        {kw}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
