import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { Mail, Copy, CheckCircle, AlertCircle, ArrowLeft, FileText, FileDown, Download } from 'lucide-react'

export default function CoverLetter() {
  const [resumeText, setResumeText] = useState('')
  const [jobTitle, setJobTitle] = useState('')
  const [companyName, setCompanyName] = useState('')
  const [loading, setLoading] = useState(false)
  const [results, setResults] = useState(null)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    // Set default values for testing
    setJobTitle('Senior Frontend Engineer')
    setCompanyName('TechInnovate Inc.')
    setResumeText(`John Doe
Email: john.doe@example.com | Phone: (555) 123-4567 | Location: San Francisco, CA
LinkedIn: linkedin.com/in/johndoe | Portfolio: johndoe.dev

PROFESSIONAL SUMMARY
Experienced software engineer with 5+ years of experience in full-stack development. Specialized in JavaScript, React, Node.js, and cloud technologies. Passionate about building scalable web applications and mentoring junior developers.

WORK EXPERIENCE
Senior Software Engineer - TechCorp Inc. (Jan 2022 - Present)
• Lead development of microservices architecture for enterprise applications
• Mentored 3 junior developers and conducted code reviews
• Improved application performance by 40% through optimization techniques
• Implemented CI/CD pipeline reducing deployment time by 60%

Full Stack Developer - StartUpXYZ (Jun 2020 - Dec 2021)
• Built React frontend and Node.js backend for SaaS platform
• Developed RESTful APIs and integrated third-party services
• Reduced page load time by 60% through performance optimization

EDUCATION
Master of Science in Computer Science - Stanford University (GPA: 3.9/4.0)
Bachelor of Science in Software Engineering - University of California (GPA: 3.8/4.0)

SKILLS
JavaScript, React, Node.js, TypeScript, Python, AWS, Docker, Kubernetes, PostgreSQL, MongoDB, Git, CI/CD

CERTIFICATIONS
AWS Certified Developer, Google Cloud Professional, React Developer Certification`)
  }, [])

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!resumeText.trim()) {
      setError('Please enter your resume text')
      return
    }

    setLoading(true)
    setError('')
    setResults(null)

    try {
      const response = await fetch('/api/cover-letter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ resumeText, jobTitle, companyName })
      })
      const data = await response.json();

      console.log("API RESPONSE:", data); // debug

      if (!response.ok) throw new Error(data.error || 'Failed to generate')

      setResults({
        cover_letter: data?.cover_letter || '',
        key_points: data?.key_points || []
      })
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(results.cover_letter)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadCoverLetter = () => {
    const content = `COVER LETTER
${'='.repeat(50)}

Target: ${jobTitle || 'N/A'}
Company: ${companyName || 'N/A'}

${'='.repeat(50)}

${results.cover_letter}
`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cover-letter-${companyName || 'general'}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const downloadFullReport = () => {
    const keyPoints = results.key_points?.map(p => `  • ${p}`).join('\n') || '  N/A'
    const report = `╔══════════════════════════════════════════════════════════════╗
║              AI COVER LETTER - GENERATION REPORT              ║
╚══════════════════════════════════════════════════════════════╝

GENERATED: ${new Date().toLocaleDateString()}
Target Job: ${jobTitle || 'N/A'}
Company: ${companyName || 'N/A'}

${'─'.repeat(66)}
📄 COVER LETTER
${'─'.repeat(66)}
${results.cover_letter}

${'─'.repeat(66)}
🔑 KEY POINTS HIGHLIGHTED
${'─'.repeat(66)}
${keyPoints}

═══════════════════════════════════════════════════════════════
          Generated by AI Resume Builder
═══════════════════════════════════════════════════════════════
`
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `cover-letter-report-${companyName || 'general'}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="py-12 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Back link */}
        <Link to="/" className="inline-flex items-center gap-2 text-text-muted hover:text-text-light transition-colors mb-8 animate-slide-in-left">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        {/* Header */}
        <div className="flex items-center gap-4 mb-8 animate-slide-up">
          <div className="w-16 h-16 rounded-xl bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center animate-float">
            <Mail className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Cover Letter Generator</h1>
            <p className="text-text-muted">Create professional cover letters tailored to any job application</p>
          </div>
        </div>

        {/* Form Card */}
        <div className="bg-bg-card border border-border rounded-2xl p-6 sm:p-8 animate-slide-up delay-100 card-lift">
          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="grid sm:grid-cols-2 gap-4 animate-slide-up delay-100">
              <div>
                <label className="block text-text-muted mb-2 font-medium">Target Job Title</label>
                <input
                  type="text"
                  value={jobTitle}
                  onChange={(e) => setJobTitle(e.target.value)}
                  placeholder="Senior Frontend Engineer"
                  className="w-full bg-bg-dark border border-border rounded-xl px-4 py-3 text-text-light focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all"
                />
              </div>
              <div>
                <label className="block text-text-muted mb-2 font-medium">Company Name</label>
                <input
                  type="text"
                  value={companyName}
                  onChange={(e) => setCompanyName(e.target.value)}
                  placeholder="TechInnovate Inc."
                  className="w-full bg-bg-dark border border-border rounded-xl px-4 py-3 text-text-light focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all"
                />
              </div>
            </div>

            <div className="animate-slide-up delay-200">
              <label className="block text-text-muted mb-2 font-medium">Your Resume</label>
              <textarea
                value={resumeText}
                onChange={(e) => setResumeText(e.target.value)}
                placeholder="Paste your resume here..."
                rows={8}
                className="w-full bg-bg-dark border border-border rounded-xl px-4 py-3 text-text-light focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all resize-none"
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="btn-gradient w-full py-4 rounded-xl font-semibold text-white flex items-center justify-center gap-2 disabled:opacity-50 btn-press transition-all duration-300 animate-slide-up delay-300"
            >
              {loading ? (
                <>
                  <div className="spinner w-5 h-5" />
                  <span>Generating...</span>
                </>
              ) : (
                <>
                  <Mail className="w-5 h-5" />
                  <span>Generate Cover Letter</span>
                </>
              )}
            </button>
          </form>

          {error && (
            <div className="mt-4 p-4 bg-red-500/10 border border-red-500 rounded-xl text-red-400 flex items-center gap-2 animate-scale-in">
              <AlertCircle className="w-5 h-5" /> {error}
            </div>
          )}
        </div>

        {/* Loading Skeleton */}
        {loading && (
          <div className="mt-8 space-y-6 animate-fade-in">
            <div className="bg-bg-card border border-border rounded-2xl overflow-hidden">
              <div className="p-5 border-b border-border">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-bg-dark animate-shimmer" />
                  <div className="space-y-2 flex-1">
                    <div className="h-4 w-32 bg-bg-dark rounded animate-shimmer" />
                    <div className="h-3 w-24 bg-bg-dark rounded animate-shimmer" />
                  </div>
                </div>
              </div>
              <div className="p-5 space-y-3">
                <div className="h-4 bg-bg-dark rounded animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-5/6 animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-4/6 animate-shimmer" />
                <div className="h-4 bg-bg-dark rounded w-3/6 animate-shimmer" />
              </div>
            </div>
          </div>
        )}

        {/* Results */}
        {results && (
          <div className="mt-8 space-y-6">
            {/* Cover Letter Card */}
            <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-scale-in card-lift">
              <div className="flex items-center justify-between p-5 border-b border-border">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center">
                    <Mail className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Cover Letter</h4>
                    <p className="text-sm text-text-muted">
                      {jobTitle && companyName ? `${jobTitle} at ${companyName}` : 'Professional cover letter'}
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={downloadCoverLetter}
                    className="flex items-center gap-2 px-3 py-2 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-lg text-emerald-400 transition-all duration-300 btn-press"
                  >
                    <FileText className="w-4 h-4" /> Letter
                  </button>
                  <button
                    onClick={downloadFullReport}
                    className="flex items-center gap-2 px-3 py-2 bg-violet-500/10 hover:bg-violet-500/20 rounded-lg text-violet-400 transition-all duration-300 btn-press"
                  >
                    <FileDown className="w-4 h-4" /> Report
                  </button>
                  <button
                    onClick={copyToClipboard}
                    className="flex items-center gap-2 px-4 py-2 bg-primary/10 hover:bg-primary/20 rounded-lg text-primary transition-all duration-300 btn-press"
                  >
                    {copied ? <CheckCircle className="w-4 h-4 animate-scale-in" /> : <Copy className="w-4 h-4" />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                </div>
              </div>
              <div className="p-5 bg-bg-dark/50">
                <div className="text-text-light leading-relaxed space-y-2">
                  {results.cover_letter?.split('\n').map((line, i) => (
                    <p key={i}>{line}</p>
                  ))}
                </div>
              </div>
            </div>

            {/* Key Points Card */}
            {results.key_points?.length > 0 && (
              <div className="bg-bg-card border border-border rounded-2xl overflow-hidden animate-slide-up delay-100 card-lift">
                <div className="flex items-center gap-3 p-5 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-amber-500 to-orange-500 flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
                    </svg>
                  </div>
                  <div>
                    <h4 className="text-lg font-semibold">Key Points Highlighted</h4>
                    <p className="text-sm text-text-muted">{results.key_points.length} points covered</p>
                  </div>
                </div>
                <div className="p-5">
                  <ul className="space-y-3">
                    {results.key_points.map((point, i) => (
                      <li
                        key={i}
                        className="bg-bg-dark/50 p-4 rounded-xl border-l-4 border-amber-500 hover:translate-x-2 transition-transform duration-300"
                        style={{ animationDelay: `${i * 100}ms` }}
                      >
                        <span className="text-text-light">{point}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
